### ISSUE TITLE
PSA-VAN.html does not show data from local drive

### ISSUE THREAD

**Issue by nona00** [morcibacsi/psa_van_bus_packet_descriptions#2]
only rotating bar shown:

![grafik](https://github.com/morcibacsi/psa_van_bus_packet_descriptions/assets/3192606/bc1b85f8-1728-492c-ac3d-0aef8ce36e88)

**Comment by morcibacsi** [comment]
You need to run it from a web server as the frame descriptors are in the json files which are retrieved via an XHR request which can't be resolved when opened directly from a drive.

**Comment by nona00** [comment]
Thank you very much for this hint. On my web server it works :-)

Perhaps you can add this information to the readme.
